
["General Settings"]
	#Apply armor effects
	applyArmorEffects = true
	#Apply attribute modifiers
	applyModifiers = true
	#Show item descriptions
	showDescriptions = true
	#Render custom capes attached to chestplates
	showCapes = true
	#Do not make capes static if Epic Fight is loaded. It is not implemented yet completely
	epicFightNotStaticCapes = false
	#Show effect particles
	showParticles = false
	#The minimum duration of the existing effect, after which it will be given again
	#Range: > 1
	effectsInterval = 241
	#Show effect icon or not
	showEffectIcon = true

